version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - github-actions
    reviewers:
      - devpow112
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - docker
    reviewers:
      - devpow112
