bash:
  - changed-files:
    - any-glob-to-any-file:
      - root/etc/s6-overlay/scripts/*
docker:
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - .dockerignore
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - .github/CODEOWNERS
      - LICENSE
github-actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/workflows/*.yml
