name: build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
      PACKAGE: ghcr.io/${{github.repository_owner}}/base-ubuntu
      DISTRIBUTION: focal
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Set up qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{env.PLATFORMS}}
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Set up cache
        uses: actions/cache@v2.1.3
        with:
          path: /tmp/.buildx-cache
          key: buildx2-${{hashFiles('Dockerfile', '.dockerignore', 'root/**')}}
          restore-keys: buildx2-
      - name: Determine package info
        id: package
        run: |
          TAGS="${PACKAGE}:latest"
          TAGS="${TAGS},${PACKAGE}:${DISTRIBUTION}-$(date +%Y%m%d)"
          echo "Tags: ${TAGS}"
          echo "##[set-output name=tags;]${TAGS}"
      - name: Build image
        id: build
        uses: docker/build-push-action@v2.2.1
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          platforms: ${{env.PLATFORMS}}
          tags: ${{steps.package.outputs.tags}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          push: false
      - name: Login into registry
        uses: docker/login-action@v1.7.0
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.CONTAINER_REGISTRY_TOKEN}}
      - name: Gather image digests
        id: digest
        run: |
          REMOTE=$(docker buildx imagetools inspect ${PACKAGE}:latest)
          REMOTE=$(echo "${REMOTE}" | grep Digest | cut -d: -f3)
          echo "Remote: ${REMOTE}"
          echo "Local: ${{steps.build.outputs.digest}}"
          echo "##[set-output name=remote;]${REMOTE}"
          echo "##[set-output name=local;]${{steps.build.outputs.digest}}"
      - name: Push image
        if: >
          github.ref == 'refs/heads/main' &&
          steps.digest.outputs.local != steps.digest.outputs.remote
        uses: docker/build-push-action@v2.2.1
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          platforms: ${{env.PLATFORMS}}
          tags: ${{steps.package.outputs.tags}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          push: true
