name: CI
on:
  workflow_call:
permissions:
  contents: read
jobs:
  check-formatting-dockerfile:
    name: Check Formatting (Dockerfile)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Check formatting
        uses: hadolint/hadolint-action@v1.6.0
  check-formatting-markdown:
    name: Check Formatting (Markdown)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: ghcr.io/devpow112/markdownlint
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Check formatting
        shell: bash
        run: find . -type f -iname '*.md' -print0 | xargs -0 markdownlint
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          version: latest
      - name: Set up cache
        uses: actions/cache@v2.1.7
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{hashFiles('Dockerfile', '.dockerignore', 'root/**')}}
          restore-keys: buildx-
      - name: Build image
        uses: docker/build-push-action@v2.9.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          push: false
