name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
permissions:
  contents: read
  packages: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      registry:
        image: registry
        ports:
          - 5000:5000
    env:
      PACKAGE: ghcr.io/${{github.repository_owner}}/base-ubuntu
      PACKAGE_TEMP: localhost:5000/${{github.repository_owner}}/base-ubuntu
      PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
    steps:
      - name: Gather info
        id: info
        run: |
          TAGS="$PACKAGE:latest"
          TAGS="$PACKAGE:focal-$(date +%Y%m%d),$TAGS"
          echo "::set-output name=tags::$TAGS"
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
        with:
          platforms: ${{env.PLATFORMS}}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          driver-opts: network=host
          version: latest
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{hashFiles('Dockerfile', '.dockerignore', 'root/**')}}
          restore-keys: buildx-
      - name: Build image
        uses: docker/build-push-action@v2.4.0
        id: build
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          platforms: ${{env.PLATFORMS}}
          tags: ${{env.PACKAGE_TEMP}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          push: true
      - name: Check digests
        id: digests
        run: |
          DIGEST=$(
            docker buildx imagetools inspect $PACKAGE_TEMP |
            grep Digest | cut -c9-
          )
          DIGEST_CURRENT=$(
            docker buildx imagetools inspect $PACKAGE |
            grep Digest | cut -c9-
          )
          [ "$DIGEST" = "$DIGEST_CURRENT" ] ||
          echo '::set-output name=changed::true'
      - name: Login to registry
        if: github.ref == 'refs/heads/main' && steps.digests.outputs.changed
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Push image
        if: github.ref == 'refs/heads/main' && steps.digests.outputs.changed
        uses: docker/build-push-action@v2.4.0
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          platforms: ${{env.PLATFORMS}}
          tags: ${{steps.info.outputs.tags}}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
          push: true
