name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
permissions:
  contents: read
jobs:
  check-formatting-dockerfile:
    name: Check Formatting (Dockerfile)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container: hadolint/hadolint:latest-debian
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Check formatting
        run: hadolint Dockerfile
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      registry:
        image: registry
        ports:
          - 5000:5000
    env:
      PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64,linux/ppc64le
      CACHE_FROM: type=local,src=/tmp/.buildx-cache
      CACHE_TO: type=local,mode=max,dest=/tmp/.buildx-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
        with:
          platforms: ${{env.PLATFORMS}}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          driver-opts: network=host
          version: latest
      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{hashFiles('Dockerfile', '.dockerignore', 'root/**')}}
          restore-keys: buildx-
      - name: Build image
        uses: docker/build-push-action@v2.4.0
        id: build
        with:
          builder: ${{steps.buildx.outputs.name}}
          context: .
          platforms: ${{env.PLATFORMS}}
          cache-from: ${{env.CACHE_FROM}}
          cache-to: ${{env.CACHE_TO}}
          push: false
