name: Pull Request
on:
  pull_request:
    branches: main
permissions:
  contents: read
  pull-requests: write
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  label:
    name: Label
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Apply labels
        uses: actions/labeler@v4.0.2
        with:
          repo-token: ${{github.token}}
