#!/bin/bash

if [ -e /.03-apply-permission-complete ]; then
  exit 0
fi

echo "Applying permissions for /config folder ..."
chown -R primary-user:primary-user /config
echo "Applying permissions for /config folder ... Done"

touch /.03-apply-permission-complete
